..  |ANTLR|                 replace:: *ANother Tool for Language Recognition*
..  _ANTLR:                 https://www.antlr.org/
..  _AppVeyor:              https://www.appveyor.com/

..  |CFD|                   replace::   *Computational Fluid Dynamics*
..  _CFD:                   https://en.wikipedia.org/wiki/Computational_fluid_dynamics

..  |CG|                    replace:: *center of gravity*

..  |CI|                    replace::   *Continuous Integration*

..  _Click:                  https://palletsprojects.com/p/click/
..  _Coveralls:             https://coveralls.io/

..  |CSG|                   replace::   *Constructive Solid Geometry*
..  _CSG:                   https://en.wikipedia.org/wiki/Constructive_solid_geometry
..  _FedEx:                 https://www.fedex.com/en-us/home.html

..  |Gadfly|                replace:: Hendersen-Glenny Gadfly
..  _Gadfly:                https://en.wikipedia.org/wiki/Henderson-Glenny_Gadfly

..	|GH|	                replace:: *GitHub*
..	_GH:	                https://github.com/

..	_Git:	                https://git-scm.com/

..  _given when then:       https://martinfowler.com/bliki/GivenWhenThen.html

..  |GUI|                   replace:: *Graphical User Interface*

..  |HAFFA|                 replace::   *Heart of America Free Flight Association*
..  _HAFFA:                 https://kcfreeflight.org/

..  _Homebrew:              https://brew.sh/

..  _Justin Lin:            https://openhome.cc/eGossip/OpenSCAD/FunctionGrapher.html

..  _Linus Torvalds:        https://en.wikipedia.org/wiki/Linus_Torvalds

..  |LPP|                   replace:: *Limited Pennyplane*

..  _Make:                  https://www.gnu.org/software/make/

..  |MMAKE|                 replace::   *Modular Make*
..  _MMAKE:                 https://github.com/rblack42/modular-make/

..  |MM|                    replace::   *Math-Magik*
..  _MM:                    https://github.com/rblack42/math-magik

..  |MMD|                   replace::   *Math-Magik Designer*
..  _MMD:                   https://pypi.org/project/mmdesigner/

..  |NFFS|                  replace::   *National Free Flight Society*
..  _NFFS:                  https://freeflight.org/

..  _numpy-stl:             https://pypi.org/project/numpy-stl/


..  |OS|                    replace::   *Open Source*

..  |OSC|                   replace::   *OpenSCAD*
..  _OSC:                   https://openscad.org/

..	|PY|	                replace::	*Python*
..	_PY:	                https://www.python.org/

..  |PyPi|                  replace:: *Python Package Index*
..  _PyPi:                  https://pypi.org/

..  _PyCharm:               https://www.jetbrains.com/pycharm/

..  _Qt:                    https://www.qt.io/

..  |RST|                   replace:: *reStructuredText*

..  _semantic versioning:   https://semver.org/

..  _Sphinx:                https://www.sphinx-doc.org/en/master/

..  |STL|                   replace::   *Standard Tessellation Library*
..  _STL:                   https://en.wikipedia.org/wiki/STL_(file_format)

..  |TDD|                   replace::   *Test Driven Development*

..  _tkinter:               https://docs.python.org/3/library/tkinter.html

..  _Travis-CI:             https://travis-ci.com/

..  _Ubuntu:                https://ubuntu.com/
